### ISSUE TITLE
Possible to Support Other Passenger Configuration Options

### ISSUE THREAD

**Issue by ksylvest** [phusion/passenger-ruby-heroku-demo#15]
How can other Passenger configuration options, such as `PassengerMaxRequests`, that are not available from the `passenger` binary be added to the `Procfile`? Running `passenger start --help` only seems to expose a few of the process management options. Thanks!

**Comment by FooBarWidget** [comment]
You can use [advanced configuration](https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#advanced_configuration) to achieve that goal.
