### ISSUE TITLE
Using a configuration file

### ISSUE THREAD

**Issue by makenosound** [phusion/passenger-ruby-heroku-demo#19]
I’d like to be able to set the `--max-pool-size` based on the `ENV` variables for my app using Heroku’s `WEB_CONCURRENCY` variable. I’m wondering if there’s an equivalent for setting configuration dynamically via a config file. Something akin to [`config/puma.rb` in Heroku’s instructions for setting up Puma](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#config).

The docs reference `Passengerfile.json`, but I’m not quite sure how that’d work with dynamic options — is there a way to do what I’m after?

Thanks!

**Comment by FooBarWidget** [comment]
Passengerfile.json is a static JSON file, and thus cannot perform any dynamic processing by itself.

But you don't need to use Passengerfile.json for this. The Procfile supports environment variable interpolation. You could pass --max-pool-size as a command line option, like this:

```
web: bundle exec passenger start --max-pool-size $WEB_CONCURRENCY
```

Or, if you're using Passenger Enterprise and want to customize the thread count too:

```
web: bundle exec passenger start --max-pool-size $WEB_CONCURRENCY --concurrency-model thread --thread-count $MAX_THREADS
```

**Comment by matthewford** [comment]
@FooBarWidget could this be added to the readme?
