### ISSUE TITLE
Passenger Enterprise only in production

### ISSUE THREAD

**Issue by cirdes** [phusion/passenger-ruby-heroku-demo#21]
I have at least 3 staging servers and I would like to use Passenger Enterprise in production and the open source in staging. 

Gemfile.rb

```
group  :production do
  gem 'passenger-enterprise-server'
end

group :staging do
  gem 'passenger'
end
```

But in the Procfile if I set thread-count I get an error. Is it possible to configure the Procfile to work with opensource and enterprise? Or to have a Procfile per environment?

```
web: bundle exec passenger start -p $PORT --max-pool-size $WEB_CONCURRENCY --min-instances $WEB_CONCURRENCY --concurrency-model thread --thread-count $MAX_THREADS
```

**Comment by OnixGH** [comment]
If you move the exec command to a shell file, you can use an `if [ "$RACK_ENV" == "development" ]; then` to differentiate between the two command lines automatically.

**Comment by cirdes** [comment]
Thanks @OnixGH, I will try that.
