### ISSUE TITLE
WEB_CONCURRENCY support

### ISSUE THREAD

**Issue by monkseal** [phusion/passenger-ruby-heroku-demo#24]
This is a question more than an issue. Is it possible to use `WEB_CONCURRENCY` environment variable in Profile so I don't have to redeploy to adjust my max-pool-size? If so, what would that look like? Would this work?

```
web: bundle exec passenger start -p $PORT --max-pool-size $WEB_CONCURRENCY
```

**Comment by FooBarWidget** [comment]
Yes that would work fine. That's how it is supposed to be used.
