### ISSUE TITLE
Passenger timing out upon starting a new dyno.

### ISSUE THREAD

**Issue by Hamada92** [phusion/passenger-ruby-heroku-demo#28]
Hey guys,

Thanks for all the great work. We are hosting a Rails app on Heroku with open source Passenger. When we boot up a new Dyno during peak time, the Passenger queue starts accumulating requests before the processes are ready to serve the requests, so we get too many timeout errors, and the queueing time on NewRelic spikes up. I think Heroku is routing requests to the new Dyno before Passenger is fully ready to process them. Any idea how to avoid this? 

Thanks

**Comment by CamJN** [comment]
As of [Passenger Enterprise 5.1.11](https://blog.phusion.nl/2017/10/16/passenger-5-1-11/#deferredportbindingstandalone) this has a dedicated workaround.

There is no support for this built-in to Passenger OSS.
