### ISSUE TITLE
Passenger Enterprise defer_port_binding not consistent on Heroku

### ISSUE THREAD

**Issue by Hamada92** [phusion/passenger-ruby-heroku-demo#30]
Hey guys,

Thanks for the great server.

We are running Passenger Enterprise with Rails 3.2 on Heroku. We have the `defer_port_binding` config to work around the problem of Heroku buffering requests too early. We recently started using a new config, `memory_limit` to restart heavy workers, and we noticed that upon new dyno boot ups, the old problem of early request buffering has come back partially, so some dynos would boot up normally, but some dyno would start accumulating requests in the queue and exhaust resources, then we'd restart that particular dyno. 

I was wondering if these two configs affect each other, or if there are any other configs that we could use on Heroku to make boot ups more stable?

**Comment by OnixGH** [comment]
@Hamada92 thanks for your question, but for Enterprise support please submit a ticket via https://www.phusionpassenger.com/support
