### ISSUE TITLE
How to pass nginx variable in request header?

### ISSUE THREAD

**Issue by Hamada92** [phusion/passenger-ruby-heroku-demo#31]
Hey guys,

we're running Passenger enterprise 5.1.12, I want to pass a new header to the app, but the following isn't working: 

```
server {
        passenger_set_header Country-Code $geoip_country_code;
}
```

How can I achieve this?

Thanks

**Comment by CamJN** [comment]
This is not currently possible. See open enhancement request here: https://github.com/phusion/passenger/issues/1779

**Comment by Hamada92** [comment]
Thanks, can I do it with Nginx's `proxy_set_header` ?
