### ISSUE TITLE
recommended max pool size for 512 mb dyno?

### ISSUE THREAD

**Issue by 34code** [phusion/passenger-ruby-heroku-demo#8]
What should be the recommended --max-pool-size for a 512 mb dyno on heroku?

**Comment by ibnukamy** [comment]
I keep having Heroku R14 (Memory quota exceeded) after using max_pool_size = 3. I just recently changed from unicorn.

@34code, are you having any problem with max_pool_size = 4?

**Comment by 34code** [comment]
Haven't tried on heroku lately but this problem does not exist on cloud foundry for my app.
